import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/Navbar";
import { authOptions } from "../auth/authOptions";
import { getServerSession } from "next-auth";
import SessionWrapper from "@/components/SessionWrappee";
import LayoutWrapper from "@/components/LayoutWrapper"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionWrapper session={session}>
          <Navbar />
          <LayoutWrapper>
            <div className="mt-[3em] ">{children}</div>
          </LayoutWrapper>
        </SessionWrapper>
      </body>
    </html>
  );
}
